name: Environment

on:
  push:
  workflow_dispatch:
    inputs:
      TARGET_ENVIRONMENT:
        type: environment
        default: staging

jobs:
  echo-environment:
    runs-on: ubuntu-latest
    environment: ${{inputs.TARGET_ENVIRONMENT}}
    steps:
      - name: Echo vars
        run:
          echo "Secret variable ${{secrets.ENV_SECRET}}"
          echo "Var variable is ${{vars.ENV_VAR}}"
