name: First workflow

on: 
  issues:
  push:
  workflow_dispatch:


jobs:
  first-job:
     runs-on: self-hosted
     steps:
       - name: First step
         run: sleep 20

  second-job:
     runs-on: self-hosted
     steps:
       - name: Second step
         run: echo "First workflow with second step"
