name: functions

on:
 workflow_dispatch:

jobs:
  echo-function:
    runs-on: self-hosted
    steps:
      -  name: failing step
         run: exit 1
      -  name: I will be skipped
         if: ${{success()}}
         run: echo "I will print if previous step failed"
      -  name: I will be success
         if: ${{failure()}}
         run: echo "I will be printed if first step failed"
      -  name: I will be always printed
         if: ${{!calcelled}}
         run: echo "I will be printed always"
