name: Template

on:
  workflow_call:
    inputs:
      message: 
        description: "Message to print"
        required: true
        type: string

jobs:
  print-message:
    runs-on: self-hosted
    steps:
      - name: print message
        run: echo "${{inputs.message}}"
